### ISSUE TITLE
Investigar tecnologías para la aplicación

### ISSUE THREAD

**Issue by Xotl** [cristito08/roomie-project#1]
* https://firebase.google.com/products/hosting/
* https://cordova.apache.org
* https://ionicframework.com
* https://reactnative.dev
* https://web.dev/progressive-web-apps/

**Comment by cristito08** [comment]
Despues de revisar las opciones que tenia, estuve indecisa entre usar ionic o progressive web apps.
Ionic era la mejor opción comparandolo con Cordova y react-native.
Las modificaciones que se deben hacer en el código en Ionic son mucho menores que en react-native, y aunque en performance esta mejor react-native, el performance de Ionic tampoco es malo. También la librería de componentes es más amplia.
Además esta Ionic React que tiene una curva de aprendizaje menor que con react native.
Entre cordova y ionic, el performance de ionic es mejor.

Me interesa aprender sobre las PWAs porque creo que poco a poco esta tomando mas fuerza... 
Tiene muchas ventajas, como la rapidez con la que carga las paginas, el espacio que ocupa en el dipositivo, se puede usar como una aplicacion nativa, tener un acceso directo en home, y si no tienes internet, puedes guardar cosas en el cache para que pueda seguir teniendo algunas funciones.

Al final termine decidiendome por las progressive web apps por que creo que tienen muchas ventajas, sirve para la aplicacion que quiero desarrollar y creo que lo que aprenda lo voy a poder aprovechar para futuros proyectos

:)
