### ISSUE TITLE
Key features que la aplicación debe tener.

### ISSUE THREAD

**Issue by Xotl** [cristito08/roomie-project#2]

**Comment by cristito08** [comment]
Por el momento creo que los features que debería tener la aplicación son:
Log in
vista de perfil: Ahi se mostraran los datos del usuario, como nombre, correo, foto y se podran editar.
Vista general del grupo de roomies: va a ser la pagina principal, donde se mostrara una vista resumida de lo que se vaya agregando al grupo, como nuevas fechas importantes, gastos que se hayan hecho etc..
calendario: se mostrara un calendario donde se podra ver si hay algo especial para algun dia, como el pago de la renta, si es el dia que van a llevar el agua, el dia que limpian la casa etc.. 
vista de cuentas $: aqui se mostraran los gastos compartidos, donde aparecera si el usuario le debe a alguno de sus roomies o le deben a el.
